services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    env_file:
      - ../backend/.env
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
