"""Initial crawl data schema with crawl_data schema

Revision ID: aad702e7f0d1
Revises: 
Create Date: 2025-09-08 09:12:12.608192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aad702e7f0d1'
down_revision: Union[str, Sequence[str], None] = '82b6043f2107'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_url', sa.String(), nullable=False),
    sa.Column('base_domain', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('total_pages', sa.Integer(), nullable=True),
    sa.Column('limits', sa.JSON(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('log_file', sa.String(), nullable=True),
    sa.Column('json_file', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='crawl_data'
    )
    op.create_index(op.f('ix_crawl_data_crawl_sessions_base_domain'), 'crawl_sessions', ['base_domain'], unique=False, schema='crawl_data')
    op.create_index(op.f('ix_crawl_data_crawl_sessions_id'), 'crawl_sessions', ['id'], unique=False, schema='crawl_data')
    op.create_index(op.f('ix_crawl_data_crawl_sessions_target_url'), 'crawl_sessions', ['target_url'], unique=False, schema='crawl_data')
    op.create_table('crawled_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('canonical_url', sa.String(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('crawled_at', sa.DateTime(), nullable=False),
    sa.Column('primary_category', sa.String(), nullable=False),
    sa.Column('secondary_categories', sa.JSON(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('signals', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['crawl_data.crawl_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='crawl_data'
    )
    op.create_index(op.f('ix_crawl_data_crawled_pages_canonical_url'), 'crawled_pages', ['canonical_url'], unique=False, schema='crawl_data')
    op.create_index(op.f('ix_crawl_data_crawled_pages_content_hash'), 'crawled_pages', ['content_hash'], unique=False, schema='crawl_data')
    op.create_index(op.f('ix_crawl_data_crawled_pages_id'), 'crawled_pages', ['id'], unique=False, schema='crawl_data')
    op.create_index(op.f('ix_crawl_data_crawled_pages_primary_category'), 'crawled_pages', ['primary_category'], unique=False, schema='crawl_data')
    op.create_index(op.f('ix_crawl_data_crawled_pages_score'), 'crawled_pages', ['score'], unique=False, schema='crawl_data')
    op.create_index(op.f('ix_crawl_data_crawled_pages_url'), 'crawled_pages', ['url'], unique=False, schema='crawl_data')
    op.create_table('page_contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('h1_text', sa.Text(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('raw_html', sa.Text(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_categories', sa.JSON(), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['crawl_data.crawled_pages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='crawl_data'
    )
    op.create_index(op.f('ix_crawl_data_page_contents_id'), 'page_contents', ['id'], unique=False, schema='crawl_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crawl_data_page_contents_id'), table_name='page_contents', schema='crawl_data')
    op.drop_table('page_contents', schema='crawl_data')
    op.drop_index(op.f('ix_crawl_data_crawled_pages_url'), table_name='crawled_pages', schema='crawl_data')
    op.drop_index(op.f('ix_crawl_data_crawled_pages_score'), table_name='crawled_pages', schema='crawl_data')
    op.drop_index(op.f('ix_crawl_data_crawled_pages_primary_category'), table_name='crawled_pages', schema='crawl_data')
    op.drop_index(op.f('ix_crawl_data_crawled_pages_id'), table_name='crawled_pages', schema='crawl_data')
    op.drop_index(op.f('ix_crawl_data_crawled_pages_content_hash'), table_name='crawled_pages', schema='crawl_data')
    op.drop_index(op.f('ix_crawl_data_crawled_pages_canonical_url'), table_name='crawled_pages', schema='crawl_data')
    op.drop_table('crawled_pages', schema='crawl_data')
    op.drop_index(op.f('ix_crawl_data_crawl_sessions_target_url'), table_name='crawl_sessions', schema='crawl_data')
    op.drop_index(op.f('ix_crawl_data_crawl_sessions_id'), table_name='crawl_sessions', schema='crawl_data')
    op.drop_index(op.f('ix_crawl_data_crawl_sessions_base_domain'), table_name='crawl_sessions', schema='crawl_data')
    op.drop_table('crawl_sessions', schema='crawl_data')
    # ### end Alembic commands ###
